apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: videocheviri-ingress
  namespace: videocheviri
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
  labels:
    app: videocheviri-backend
spec:
  ingressClassName: nginx
  rules:
    - host: videocheviri.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: videocheviri-backend
                port:
                  number: 8000
